services:
  - type: web
    name: Personal-Ai-assistant
    env: python3
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
